language: python
dist: focal

python:
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - sudo apt-get update
  - sudo apt-get install default-jre r-base-dev -y

install:
  - pip install -e .
  - pip install pytest

script:
  - pytest tests/